### ISSUE TITLE
Did you get a 3 year old to write this?

### ISSUE THREAD

**Issue by dr-NHA** [szaaamerik/Memory#1]
Terrible shit,
Cant believe your gon put this in that tool of yours,
Pretty sad ngl,

Why is this just a header file?
Im so confused on your thought process here?
If your just using it to import functions to c# thats a bit slow in the brain when its not going to benefiet you in any way,
Instead why dont u focus your time on something productive,
Maybe even try skidding my memory library from my private tool XD

**Comment by szaaamerik** [comment]
What a pathetic loser you are, your opinion means absolutely nothing to me, and I couldn't care less about your ignorant and uninformed criticism.

For your information, my memory library is not going to be used in C# "XD", so your entire argument is completely irrelevant. That would be a waste of time and resources. It's clear that you have no idea what you're talking about, and you're just trying to troll me because you're jealous of my superior skills.

Secondly, why are you so confused about my thought process? It's simple: I created a header file because it's the most efficient way to organize and share code. "Oh no he didn't create an additional .cpp file for it boo hoo it's time to hate on him". If you don't understand that, then maybe you should go back to school.

Instead of wasting your time hating on me, why don't you focus on improving your own pathetic coding abilities? Maybe then you'll be able to create something even remotely impressive. But I doubt it, because you're clearly a worthless and untalented brain dead fuck who will never amount to anything in the world.

Let's not forget your sad thought process of the whole AIO being just SQL mods. It's so much more complex than your tiny, pea-sized brain can handle. Why don't you try doing something useful like creating mission, trailblazer, race time scales or danger sign multipliers using SQL? Oh wait, you can't because it's not possible. 

It's people like you who give modding a bad name. You're just a narrow-minded, ignorant fat retard who thinks they know everything. Newsflash: you don't. You're just a useless piece of trash who contributes nothing of value to the community.

So go ahead and keep hating on me, loser. In conclusion, fuck you and your ignorant, narrow-minded opinions. You're not worth our time or energy.
